server:
 port:
  8080
spring:
  profiles:
    active: local
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      add-mappings: true